// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2018-07-27 15:17:27

package com.mpaas.demo.rpc.request;

import com.mpaas.demo.rpc.model.AccountInfo;

public class PostPostReq {
    public AccountInfo _requestBody;

}