// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2018-07-27 15:17:27

package com.mpaas.demo.rpc.model;

public class UserInfo {
    public String name;
    public Integer age;
    public VipInfo vipInfo;

}