// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2018-09-21 17:32:28

package com.mpaas.demo.rpc;

import com.alipay.mobile.framework.service.annotation.OperationType;
import com.alipay.mobile.framework.service.annotation.SignCheck;
import com.mpaas.demo.rpc.model.UserInfo;
import com.mpaas.demo.rpc.request.GetIdGetReq;
import com.mpaas.demo.rpc.request.PostPostReq;

public interface RpcDemoClient {

    @SignCheck
    @OperationType("com.antcloud.request.exception")
    public String exceptionGet();


    @SignCheck
    @OperationType("com.antcloud.request.get")
    public String getIdGet(GetIdGetReq requestParam);


    @SignCheck
    @OperationType("com.antcloud.request.post")
    public UserInfo postPost(PostPostReq requestParam);


}